from datetime import datetime, date
from sqlalchemy import Column, Integer, String, Float, Boolean, Date, DateTime, ForeignKey, Text
from sqlalchemy.orm import relationship
from app.database import Base


class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    username = Column(String(50), unique=True, index=True, nullable=False)
    email = Column(String(120), unique=True, index=True, nullable=False)
    full_name = Column(String(100), nullable=True)
    hashed_password = Column(String(255), nullable=False)
    role = Column(String(20), default="user")  # "admin" or "user"
    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationships
    products = relationship("Product", back_populates="owner", cascade="all, delete-orphan")
    shopping_items = relationship("ShoppingItem", back_populates="user", cascade="all, delete-orphan")
    expenses = relationship("ExpenseLog", back_populates="user", cascade="all, delete-orphan")


class Category(Base):
    __tablename__ = "categories"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(60), unique=True, index=True, nullable=False)
    icon = Column(String(10), default="📦")
    description = Column(String(255), nullable=True)

    # Relationships
    products = relationship("Product", back_populates="category")
    shopping_items = relationship("ShoppingItem", back_populates="category")
    expenses = relationship("ExpenseLog", back_populates="category")


class Product(Base):
    __tablename__ = "products"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    category_id = Column(Integer, ForeignKey("categories.id"), nullable=False, index=True)
    name = Column(String(120), index=True, nullable=False)
    brand = Column(String(80), nullable=True)
    quantity = Column(Float, nullable=False, default=1.0)
    unit = Column(String(20), default="kg")  # kg, g, L, ml, pcs, packets, bottles
    min_quantity = Column(Float, default=1.0)  # low stock threshold
    unit_price = Column(Float, default=0.0)  # in INR
    purchase_date = Column(Date, default=date.today, nullable=False)
    expiry_date = Column(Date, index=True, nullable=False)
    barcode = Column(String(64), index=True, nullable=True)
    storage_location = Column(String(50), default="Pantry")  # Pantry, Refrigerator, Freezer
    notes = Column(Text, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    owner = relationship("User", back_populates="products")
    category = relationship("Category", back_populates="products")


class ShoppingItem(Base):
    __tablename__ = "shopping_items"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    product_id = Column(Integer, ForeignKey("products.id"), nullable=True)
    product_name = Column(String(120), nullable=False)
    category_id = Column(Integer, ForeignKey("categories.id"), nullable=True)
    target_quantity = Column(Float, default=1.0)
    unit = Column(String(20), default="kg")
    estimated_price = Column(Float, default=0.0)
    is_purchased = Column(Boolean, default=False)
    auto_added = Column(Boolean, default=False)  # True if generated by low stock alert
    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationships
    user = relationship("User", back_populates="shopping_items")
    category = relationship("Category", back_populates="shopping_items")


class ExpenseLog(Base):
    __tablename__ = "expense_logs"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    product_id = Column(Integer, ForeignKey("products.id"), nullable=True)
    product_name = Column(String(120), nullable=False)
    category_id = Column(Integer, ForeignKey("categories.id"), nullable=True)
    amount = Column(Float, nullable=False, default=0.0)  # total cost
    expense_date = Column(Date, default=date.today, index=True, nullable=False)
    payment_method = Column(String(30), default="UPI")  # UPI, Cash, Card, NetBanking
    notes = Column(String(255), nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationships
    user = relationship("User", back_populates="expenses")
    category = relationship("Category", back_populates="expenses")
